!-----------------------------------------------------------------------------
! (C) Crown copyright 2026 Met Office. All rights reserved.
! The file LICENCE, distributed with this code, contains details of the terms
! under which the code may be used.
!-----------------------------------------------------------------------------

!> @brief   Convert temperature on geopotential height to temperature on
!>          physical height
!> @details The input temperature has been generated by a model
!>          with constant gravity. For such a model physical height and
!>          geopotential height are identical. In this kernel gravity is
!>          assumed to vary correctly with height, so that physical and
!>          geopotential heights are no longer identical. The conjecture
!>          behind this kernel is that absolute temperature should be
!>          the same at the same geopotential height, regardless of
!>          whether gravity is constant or height varying.
!>          To map temperature from constant to height-varying gravity,
!>          two steps are required:
!>          (1) Find the physical height corresponding to a given
!>              geopotential height, where gravity is height-varying.
!>              This is done for each of the geopotential heights
!>              corresponding to the input temperature data. Since the
!>              input temperature profile is assumed to come from a
!>              constant gravity model, these geopotential heights are
!>              identical with the heights of the model layer boundaries.
!>          (2) Interpolate the temperature data from the physical heights
!>              calculated above to the heights of model layer boundaries.

module regrav_geopot_kernel_mod

use argument_mod,         only: arg_type,              &
                                GH_FIELD, GH_REAL,     &
                                GH_READ, GH_READWRITE, &
                                GH_SCALAR,             &
                                CELL_COLUMN
use constants_mod,        only: r_def, i_def
use fs_continuity_mod,    only: Wtheta
use kernel_mod,           only: kernel_type

implicit none

private

!-------------------------------------------------------------------------------
! Public types
!-------------------------------------------------------------------------------
type, public, extends(kernel_type) :: regrav_geopot_kernel_type
  private
  type(arg_type) :: meta_args(3) = (/                      &
       arg_type(GH_FIELD,  GH_REAL, GH_READWRITE, Wtheta), &
       arg_type(GH_FIELD,  GH_REAL, GH_READ,      Wtheta), &
       arg_type(GH_SCALAR, GH_REAL, GH_READ)               &
       /)
  integer :: operates_on = CELL_COLUMN
contains
  procedure, nopass :: regrav_geopot_code
end type

!-------------------------------------------------------------------------------
! Contained functions/subroutines
!-------------------------------------------------------------------------------
public :: regrav_geopot_code

contains

!> @param[in]  nlayers        Number of layers
!> @param[in,out] temperature Absolute temperature field
!> @param[in]  height_wth     Height coordinate in wth
!> @param[in]  planet_radius  Radius of the planet
!> @param[in]  ndf_wt         Number of degrees of freedom per cell for wtheta
!> @param[in]  undf_wt        Total number of degrees of freedom for wtheta
!> @param[in]  map_wt         Dofmap for the cell at column base for wt
subroutine regrav_geopot_code( nlayers,       &
                               temperature,   &
                               height_wth,    &
                               planet_radius, &
                               ndf_wt,        &
                               undf_wt,       &
                               map_wt )

  implicit none

  ! Arguments
  integer(kind=i_def), intent(in)    :: nlayers, &
                                        ndf_wt,  &
                                        undf_wt
  real(kind=r_def),    intent(inout) :: temperature(undf_wt)
  real(kind=r_def),    intent(in)    :: height_wth(undf_wt)
  real(kind=r_def),    intent(in)    :: planet_radius
  integer(kind=i_def), intent(in)    :: map_wt(ndf_wt)

  ! Internal variables
  integer(kind=i_def) :: k
  real(kind=r_def)    :: height_phys(0:nlayers)
  real(kind=r_def)    :: temp(0:nlayers)

  ! Physical height corresponding to geopotential height = height_wth
  do k = 0, nlayers
    height_phys(k) = height_wth(map_wt(1)+k) / &
                     ( 1.0_r_def - height_wth(map_wt(1)+k) / planet_radius )
  end do

! Temporary storage for T
  do k = 0, nlayers
    temp(k) = temperature( map_wt(1) + k )
  end do

  ! Interpolate temperature from newly computed grid back onto model grid
  call interp( nlayers+1, height_phys, temp, nlayers+1, height_wth, temperature )

end subroutine regrav_geopot_code

subroutine interp( nin, zin, fin, nout, zout, fout )

implicit none

integer(kind=i_def), intent(in)    :: nin, nout
real(kind=r_def),    intent(in)    :: zin(nin), fin(nin), zout(nout)
real(kind=r_def),    intent(inout) :: fout(nout)

integer(kind=i_def) :: kout, kin
real(kind=r_def)    :: xi

do kout = 1, nout
  if ( zout(kout) <= zin(1) ) then
    fout(kout) = fin(1)
  else if ( zout(kout) >= zin(nin) ) then
    fout(kout) = fin(nin)
  else
    do kin = 1, nin - 1
      if ( zin(kin+1) > zout(kout) ) then
        xi = ( zout(kout) - zin(kin) ) / ( zin(kin+1) - zin(kin) )
        fout(kout) = ( 1.0_r_def - xi ) * fin(kin) + xi * fin(kin+1)
        exit
      end if
    end do
  end if
end do

end subroutine interp

end module regrav_geopot_kernel_mod
